"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class synced_proprioceptive_lcmt(object):
    __slots__ = ["num_legs", "timestamp", "contact", "q", "qd", "p", "v", "tau_est", "quat", "rpy", "omega", "acc", "good_packets", "bad_packets"]

    __typenames__ = ["int8_t", "double", "boolean", "float", "float", "float", "float", "float", "float", "float", "float", "float", "int64_t", "int64_t"]

    __dimensions__ = [None, None, ["num_legs"], [12], [12], [12], [12], [12], [4], [3], [3], [3], None, None]

    def __init__(self):
        self.num_legs = 0
        self.timestamp = 0.0
        self.contact = []
        self.q = [ 0.0 for dim0 in range(12) ]
        self.qd = [ 0.0 for dim0 in range(12) ]
        self.p = [ 0.0 for dim0 in range(12) ]
        self.v = [ 0.0 for dim0 in range(12) ]
        self.tau_est = [ 0.0 for dim0 in range(12) ]
        self.quat = [ 0.0 for dim0 in range(4) ]
        self.rpy = [ 0.0 for dim0 in range(3) ]
        self.omega = [ 0.0 for dim0 in range(3) ]
        self.acc = [ 0.0 for dim0 in range(3) ]
        self.good_packets = 0
        self.bad_packets = 0

    def encode(self):
        buf = BytesIO()
        buf.write(synced_proprioceptive_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bd", self.num_legs, self.timestamp))
        buf.write(struct.pack('>%db' % self.num_legs, *self.contact[:self.num_legs]))
        buf.write(struct.pack('>12f', *self.q[:12]))
        buf.write(struct.pack('>12f', *self.qd[:12]))
        buf.write(struct.pack('>12f', *self.p[:12]))
        buf.write(struct.pack('>12f', *self.v[:12]))
        buf.write(struct.pack('>12f', *self.tau_est[:12]))
        buf.write(struct.pack('>4f', *self.quat[:4]))
        buf.write(struct.pack('>3f', *self.rpy[:3]))
        buf.write(struct.pack('>3f', *self.omega[:3]))
        buf.write(struct.pack('>3f', *self.acc[:3]))
        buf.write(struct.pack(">qq", self.good_packets, self.bad_packets))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != synced_proprioceptive_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return synced_proprioceptive_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = synced_proprioceptive_lcmt()
        self.num_legs, self.timestamp = struct.unpack(">bd", buf.read(9))
        self.contact = map(bool, struct.unpack('>%db' % self.num_legs, buf.read(self.num_legs)))
        self.q = struct.unpack('>12f', buf.read(48))
        self.qd = struct.unpack('>12f', buf.read(48))
        self.p = struct.unpack('>12f', buf.read(48))
        self.v = struct.unpack('>12f', buf.read(48))
        self.tau_est = struct.unpack('>12f', buf.read(48))
        self.quat = struct.unpack('>4f', buf.read(16))
        self.rpy = struct.unpack('>3f', buf.read(12))
        self.omega = struct.unpack('>3f', buf.read(12))
        self.acc = struct.unpack('>3f', buf.read(12))
        self.good_packets, self.bad_packets = struct.unpack(">qq", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if synced_proprioceptive_lcmt in parents: return 0
        tmphash = (0xe5b50cf5e957c239) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if synced_proprioceptive_lcmt._packed_fingerprint is None:
            synced_proprioceptive_lcmt._packed_fingerprint = struct.pack(">Q", synced_proprioceptive_lcmt._get_hash_recursive([]))
        return synced_proprioceptive_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

